import Head from 'next/head'
import ResumePage from './ResumePage'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {
  AiFillTwitterCircle, 
  AiFillLinkedin, 
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai"
import Image from "next/image";
import { useState } from "react";
import deved from '../public/dev-ed-wave.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import design from '../public/design.png';
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Zack Mertz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>
              <a href='/'>Developed by Zack Mertz</a>
            </h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill 
              onClick={() => setDarkMode(!darkMode)} 
              className='cursor-pointer text-xl'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='/ResumePage'>
                Resumé
              </a></li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Zack Mertz</h2>
            <h3 className='text-2xl py-2'>Software Developer</h3>
            <p className='text-md py-3 leading-8 text-gray-800'>
              I'm a recently graduated college student of computer science.
              Get to know me and see some of my work down below!
            </p>
          </div>

          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden'>
            <Image src={deved} layout='fill' objectFit='cover'/>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-6 text-gray-600'>
            <a href="https://www.linkedin.com/in/zack-mertz-490b19205/"><AiFillLinkedin /></a>
            <a href="https://github.com/zmertz/"><AiFillGithub /></a>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>Specialized Skills</h3>
            <p className='text-md py-2 leading-8 text-gray-80'>
              During my coursework in college, I worked on many different projects
              that helped me get to where I am now in my career.
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <center><Image src={design} width={100} height={100} /></center>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Web Design
              </h3>
              <p className="py-2">
                Creating designs following core design theory.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">HTML, CSS, JavaScript</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Typescript</p>
              <p className="text-gray-800 py-1">Tailwind</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <center><Image src={code} width={100} height={100} /></center>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Software Development
              </h3>
              <p className="py-2">
                Performing quality work with tried and true tech.
              </p>
              <h4 className="py-4 text-teal-600">Languages I Use</h4>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">C/C++</p>
              <p className="text-gray-800 py-1">SQL</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <center><Image src={consulting} width={100} height={100} /></center>
              <h3 className="text-lg font-medium pt-8 pb-2 ">Lots More!</h3>
              <p className="py-2">
                I have picked up a myriad of other skills in the tech world.
              </p>
              <h4 className="py-4 text-teal-600">Other proficient areas</h4>
              <p className="text-gray-800 py-1">UI/UX Design</p>
              <p className="text-gray-800 py-1">Data Science</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Android Dev</p>
            </div>
          </div>
        </section>

        <section className='py-10'>
        <div>
            <h3 className="text-3xl py-1 ">Portfolio</h3>
            <p className="text-md py-2 leading-8">
              Since the beginning of my journey as a developer, I've gained skills in 
              front-end, back-end, web development, UI/UX design, and even worked on a 
              small <span className="underline text-teal-500">
                <a href="https://knightscode.natehroylance.com/#/home/register">
                startup project.</a></span>
            </p>
            <p className="text-md py-2 leading-8">
              Take a look below at some of the projects I have worked on.
            </p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">

            <div className="basis-1/3 flex-1 max-h-sm max-w-sm ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>

            <div className="basis-1/3 flex-1 max-h-xlg max-w-xlg">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>

            <div className="basis-1/3 flex-1 max-h-sm max-w-sm ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>

          </div>
        </section>
      </main>
    </div>
  )
}
