import React from "react";
import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import resumePic from '../public/resume.png'

function ResumePage() {

  return (
    <div>
      <Head>
        <title>Zack Mertz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>
              <a href='/'>Developed by Zack Mertz</a>
            </h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill 
              className='cursor-pointer text-xl'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='/ResumePage'>
                Resume
              </a></li>
            </ul>
          </nav>

          <div className='text-center p-5'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Resume</h2>
            <p className='text-teal-500 underline'>
              <a href="/resume.pdf" download>(download)</a>
            </p>
          </div>

          <div className='mx-auto text-center'>
            <center><Image src={resumePic}/></center>
          </div>

        </section>
      </main>
    </div>
  );

 }
 export default ResumePage;